<!DOCTYPE html> <html> <head>

<!-- Test infrastructure -->
<script src="../external/qunit.js" type="text/javascript"></script>
<link  href="../external/qunit.css" type="text/css" rel="stylesheet" media="screen" />
<script src="../external/jsmockito-1.0.4.js" type="text/javascript"></script>
<script src="../external/jshamcrest-0.5.2.js" type="text/javascript"></script>
<script src="qunit-additions.js" type="text/javascript"></script>

<!-- External Dependencies of the code under test -->
<script src="../external/jquery.js" type="text/javascript"></script>
<script src="../external/jquery-ui.js" type="text/javascript"></script>
<link  href="../external/jquery-ui.css" type="text/css" rel="stylesheet" media="screen" />
<script src="../external/jquery.rdfquery.rules-1.0.js" type="text/javascript"></script>
<script src="../external/jquery.caret.js" type="text/javascript"></script>
<script src="../external/subarray.js" type="text/javascript"></script>
<script src="../external/underscore.js" type="text/javascript"></script>

<!-- Code under test -->

<!-- <script src="../notepad/notepad-rdf.js" type="text/javascript"></script> -->

<!-- Tests -->

<script>
    var log;
    $(document).ready(function() {

        log = console;

        JsMockito.Integration.QUnit();
        JsHamcrest.Integration.QUnit();

        function functionThatThrows() {
            throw new Error("an expection");   // I can break on this point (when I set trynocatch=true and set debugger to break on all uncaught)
        }
        function anotherFunction() {
            // code
        }
        test("using hamcrest's matchers", function() {
            assertThat([2,3,4], hasItem(3));
            assertThat([2,{a:3},4], hasItem(hasMember('a', equalTo(3))));
            assertThat([2,{a:3},4], not(hasItem(hasMember('a', equalTo(4)))));
            // We don't have the latest version of JsHamcrest
        });

        var aMockFunction = mock(anotherFunction);
        skippedTest("debugger and framework combination", function() {
            // This error simply produces "died on test #1"
            //functionThatThrows();                                   // can break inside of this

            // setting the test config throwonfail to true, all the following with throw
            equal(1,2, "a test");                                   // test: break here when setting
            assertThat("1", equalTo("2"), "a test expression");     // test: break at this point by 
            verify(aMockFunction, times(5));                        // test: break here too

        });
        skippedTest("JsMockito verifier doesn't throw but uses QUnit.ok/fail instead", function() {
            expect(2);
            var mockLog = mock(log);
            mockLog.debug('hello');
            verify(mockLog, times(1)).debug();

            // Comment the following line to test that verify uses QUnit.ok
            mockLog.warn('hello'); 
            verify(mockLog, times(1)).warn();
        });

        skippedTest("pass a message when verifying interaction", function() {
            var mockLog = mock(log);
            mockLog.debug('hello');
            verify(mockLog, times(1), "called debug once").debug();
        });

    });
</script>

</head>
<body>
    <h1 id="qunit-header">QUnit example</h1>
    <h2 id="qunit-banner"></h2>
    <div id="qunit-testrunner-toolbar"></div>
    <h2 id="qunit-userAgent"></h2>
    <ol id="qunit-tests"></ol>
    <div id="qunit-fixture">test markup, will be hidden</div>
    <div id="notepad-container"><div id="notepad"/></div>
</body>

</html>